\c bus_ticket_booth


-- Додавання автобусів
INSERT INTO buses (bus_serial_number, seat_capacity) VALUES ('BUS-0001', 22);
INSERT INTO buses (bus_serial_number, seat_capacity) VALUES ('BUS-0002', 58);
INSERT INTO buses (bus_serial_number, seat_capacity) VALUES ('BUS-0003', 48);
INSERT INTO buses (bus_serial_number, seat_capacity) VALUES ('BUS-0004', 45);
INSERT INTO buses (bus_serial_number, seat_capacity) VALUES ('BUS-0005', 49);
INSERT INTO buses (bus_serial_number, seat_capacity) VALUES ('BUS-0006', 60);
INSERT INTO buses (bus_serial_number, seat_capacity) VALUES ('BUS-0007', 58);
INSERT INTO buses (bus_serial_number, seat_capacity) VALUES ('BUS-0008', 52);
INSERT INTO buses (bus_serial_number, seat_capacity) VALUES ('BUS-0009', 30);
INSERT INTO buses (bus_serial_number, seat_capacity) VALUES ('BUS-0010', 32);
INSERT INTO buses (bus_serial_number, seat_capacity) VALUES ('BUS-0011', 47);
INSERT INTO buses (bus_serial_number, seat_capacity) VALUES ('BUS-0012', 32);
INSERT INTO buses (bus_serial_number, seat_capacity) VALUES ('BUS-0013', 28);
INSERT INTO buses (bus_serial_number, seat_capacity) VALUES ('BUS-0014', 36);
INSERT INTO buses (bus_serial_number, seat_capacity) VALUES ('BUS-0015', 50);
INSERT INTO buses (bus_serial_number, seat_capacity) VALUES ('BUS-0016', 24);
INSERT INTO buses (bus_serial_number, seat_capacity) VALUES ('BUS-0017', 37);
INSERT INTO buses (bus_serial_number, seat_capacity) VALUES ('BUS-0018', 56);
INSERT INTO buses (bus_serial_number, seat_capacity) VALUES ('BUS-0019', 24);
INSERT INTO buses (bus_serial_number, seat_capacity) VALUES ('BUS-0020', 46);
INSERT INTO buses (bus_serial_number, seat_capacity) VALUES ('BUS-0021', 42);
INSERT INTO buses (bus_serial_number, seat_capacity) VALUES ('BUS-0022', 60);
INSERT INTO buses (bus_serial_number, seat_capacity) VALUES ('BUS-0023', 48);
INSERT INTO buses (bus_serial_number, seat_capacity) VALUES ('BUS-0024', 21);
INSERT INTO buses (bus_serial_number, seat_capacity) VALUES ('BUS-0025', 20);
INSERT INTO buses (bus_serial_number, seat_capacity) VALUES ('BUS-0026', 32);
INSERT INTO buses (bus_serial_number, seat_capacity) VALUES ('BUS-0027', 36);
INSERT INTO buses (bus_serial_number, seat_capacity) VALUES ('BUS-0028', 29);
INSERT INTO buses (bus_serial_number, seat_capacity) VALUES ('BUS-0029', 47);
INSERT INTO buses (bus_serial_number, seat_capacity) VALUES ('BUS-0030', 59);


-- Додавання зупинок
INSERT INTO stops (stop_name) VALUES ('Kyiv');
INSERT INTO stops (stop_name) VALUES ('Lviv');
INSERT INTO stops (stop_name) VALUES ('Kharkiv');
INSERT INTO stops (stop_name) VALUES ('Odesa');
INSERT INTO stops (stop_name) VALUES ('Dnipro');
INSERT INTO stops (stop_name) VALUES ('Zaporizhzhia');
INSERT INTO stops (stop_name) VALUES ('Ivano-Frankivsk');
INSERT INTO stops (stop_name) VALUES ('Ternopil');
INSERT INTO stops (stop_name) VALUES ('Lutsk');
INSERT INTO stops (stop_name) VALUES ('Rivne');
INSERT INTO stops (stop_name) VALUES ('Chernivtsi');
INSERT INTO stops (stop_name) VALUES ('Khmelnytskyi');
INSERT INTO stops (stop_name) VALUES ('Zhytomyr');
INSERT INTO stops (stop_name) VALUES ('Sumy');
INSERT INTO stops (stop_name) VALUES ('Vinnytsia');
INSERT INTO stops (stop_name) VALUES ('Poltava');
INSERT INTO stops (stop_name) VALUES ('Chernihiv');
INSERT INTO stops (stop_name) VALUES ('Cherkasy');
INSERT INTO stops (stop_name) VALUES ('Mykolaiv');
INSERT INTO stops (stop_name) VALUES ('Kropyvnytskyi');


-- Додавання маршрутів
INSERT INTO routes (route_name) VALUES ('Route 1');
INSERT INTO routes (route_name) VALUES ('Route 2');
INSERT INTO routes (route_name) VALUES ('Route 3');
INSERT INTO routes (route_name) VALUES ('Route 4');
INSERT INTO routes (route_name) VALUES ('Route 5');
INSERT INTO routes (route_name) VALUES ('Route 6');
INSERT INTO routes (route_name) VALUES ('Route 7');
INSERT INTO routes (route_name) VALUES ('Route 8');
INSERT INTO routes (route_name) VALUES ('Route 9');
INSERT INTO routes (route_name) VALUES ('Route 10');


-- Додавання зупинок для кожного маршруту
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (1, 2, 1, 70);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (1, 3, 2, 65);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (1, 5, 3, 170);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (1, 7, 4, 143);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (2, 2, 1, 60);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (2, 4, 2, 90);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (2, 6, 3, 130);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (2, 8, 4, 60);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (2, 10, 5, 85);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (3, 18, 1, 110);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (3, 6, 2, 108);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (3, 4, 3, 166);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (3, 14, 4, 166);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (3, 9, 5, 94);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (3, 8, 6, 129);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (3, 10, 7, 117);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (3, 15, 8, 180);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (3, 19, 9, 120);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (3, 11, 10, 115);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (3, 1, 11, 81);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (4, 8, 1, 100);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (4, 3, 2, 66);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (4, 4, 3, 177);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (4, 16, 4, 111);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (4, 15, 5, 112);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (4, 10, 6, 103);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (4, 18, 7, 91);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (4, 7, 8, 63);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (4, 1, 9, 180);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (4, 2, 10, 161);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (4, 12, 11, 69);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (4, 9, 12, 104);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (5, 19, 1, 88);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (5, 15, 2, 123);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (5, 10, 3, 190);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (5, 8, 4, 86);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (5, 7, 5, 84);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (5, 6, 6, 70);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (5, 3, 7, 169);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (5, 1, 8, 71);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (5, 18, 9, 186);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (5, 13, 10, 86);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (5, 14, 11, 79);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (6, 2, 1, 113);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (6, 1, 2, 76);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (6, 4, 3, 154);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (6, 9, 4, 101);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (6, 15, 5, 148);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (6, 18, 6, 121);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (6, 14, 7, 66);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (6, 17, 8, 180);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (6, 13, 9, 119);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (6, 7, 10, 142);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (6, 6, 11, 165);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (6, 5, 12, 186);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (7, 5, 1, 62);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (7, 6, 2, 135);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (7, 17, 3, 152);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (7, 14, 4, 174);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (7, 15, 5, 154);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (7, 9, 6, 90);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (7, 7, 7, 96);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (7, 12, 8, 119);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (7, 10, 9, 137);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (7, 8, 10, 81);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (7, 18, 11, 117);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (7, 2, 12, 74);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (8, 16, 1, 89);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (8, 14, 2, 180);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (8, 6, 3, 135);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (8, 8, 4, 137);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (8, 1, 5, 129);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (8, 10, 6, 63);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (9, 13, 1, 70);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (9, 16, 2, 166);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (9, 14, 3, 176);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (9, 18, 4, 190);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (9, 17, 5, 61);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (9, 7, 6, 145);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (9, 19, 7, 161);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (9, 15, 8, 65);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (9, 12, 9, 172);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (10, 19, 1, 138);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (10, 15, 2, 81);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (10, 12, 3, 133);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (10, 18, 4, 114);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (10, 11, 5, 171);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (10, 14, 6, 156);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (10, 17, 7, 115);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (10, 7, 8, 185);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (10, 1, 9, 173);
INSERT INTO routes_stops (route_id, stop_id, sequence_number, departure_minutes_offset) VALUES (10, 10, 10, 113);

/*
-- Додавання рейсів
INSERT INTO schedule (route_id, bus_id, departure_datetime) VALUES (1, 27, '2024-03-20 18:00:00');
INSERT INTO schedule (route_id, bus_id, departure_datetime) VALUES (1, 4, '2024-03-20 10:15:00');
INSERT INTO schedule (route_id, bus_id, departure_datetime) VALUES (2, 8, '2024-03-20 09:30:00');
INSERT INTO schedule (route_id, bus_id, departure_datetime) VALUES (2, 25, '2024-03-20 19:40:00');
INSERT INTO schedule (route_id, bus_id, departure_datetime) VALUES (3, 28, '2024-03-20 17:20:00');
INSERT INTO schedule (route_id, bus_id, departure_datetime) VALUES (3, 24, '2024-03-20 13:00:00');
INSERT INTO schedule (route_id, bus_id, departure_datetime) VALUES (3, 12, '2024-03-20 01:40:00');
INSERT INTO schedule (route_id, bus_id, departure_datetime) VALUES (4, 30, '2024-03-20 09:25:00');
INSERT INTO schedule (route_id, bus_id, departure_datetime) VALUES (4, 7, '2024-03-20 10:15:00');
INSERT INTO schedule (route_id, bus_id, departure_datetime) VALUES (4, 20, '2024-03-20 23:05:00');
INSERT INTO schedule (route_id, bus_id, departure_datetime) VALUES (5, 16, '2024-03-20 10:55:00');
INSERT INTO schedule (route_id, bus_id, departure_datetime) VALUES (5, 1, '2024-03-20 11:25:00');
INSERT INTO schedule (route_id, bus_id, departure_datetime) VALUES (6, 29, '2024-03-20 18:10:00');
INSERT INTO schedule (route_id, bus_id, departure_datetime) VALUES (7, 3, '2024-03-20 15:10:00');
INSERT INTO schedule (route_id, bus_id, departure_datetime) VALUES (8, 17, '2024-03-20 17:00:00');
INSERT INTO schedule (route_id, bus_id, departure_datetime) VALUES (8, 15, '2024-03-20 10:55:00');
INSERT INTO schedule (route_id, bus_id, departure_datetime) VALUES (8, 18, '2024-03-20 15:00:00');
INSERT INTO schedule (route_id, bus_id, departure_datetime) VALUES (9, 13, '2024-03-20 19:50:00');
INSERT INTO schedule (route_id, bus_id, departure_datetime) VALUES (10, 9, '2024-03-20 15:00:00');
INSERT INTO schedule (route_id, bus_id, departure_datetime) VALUES (10, 2, '2024-03-20 11:45:00');
*/

-- Додавання рейсів з поточною датою і початковим часом
INSERT INTO schedule (route_id, bus_id, departure_datetime) VALUES (1, 27, DATE_TRUNC('day', CURRENT_TIMESTAMP) + interval '1 day' + TIME '18:00:00');
INSERT INTO schedule (route_id, bus_id, departure_datetime) VALUES (1, 4, DATE_TRUNC('day', CURRENT_TIMESTAMP) + interval '1 day' + TIME '10:15:00');
INSERT INTO schedule (route_id, bus_id, departure_datetime) VALUES (2, 8, DATE_TRUNC('day', CURRENT_TIMESTAMP) + interval '1 day' + TIME '09:30:00');
INSERT INTO schedule (route_id, bus_id, departure_datetime) VALUES (2, 25, DATE_TRUNC('day', CURRENT_TIMESTAMP) + interval '1 day' + TIME '19:40:00');
INSERT INTO schedule (route_id, bus_id, departure_datetime) VALUES (3, 28, DATE_TRUNC('day', CURRENT_TIMESTAMP) + interval '1 day' + TIME '17:20:00');
INSERT INTO schedule (route_id, bus_id, departure_datetime) VALUES (3, 24, DATE_TRUNC('day', CURRENT_TIMESTAMP) + interval '1 day' + TIME '13:00:00');
INSERT INTO schedule (route_id, bus_id, departure_datetime) VALUES (3, 12, DATE_TRUNC('day', CURRENT_TIMESTAMP) + interval '1 day' + TIME '01:40:00');
INSERT INTO schedule (route_id, bus_id, departure_datetime) VALUES (4, 30, DATE_TRUNC('day', CURRENT_TIMESTAMP) + interval '1 day' + TIME '09:25:00');
INSERT INTO schedule (route_id, bus_id, departure_datetime) VALUES (4, 7, DATE_TRUNC('day', CURRENT_TIMESTAMP) + interval '1 day' + TIME '10:15:00');
INSERT INTO schedule (route_id, bus_id, departure_datetime) VALUES (4, 20, DATE_TRUNC('day', CURRENT_TIMESTAMP) + interval '1 day' + TIME '23:05:00');
INSERT INTO schedule (route_id, bus_id, departure_datetime) VALUES (5, 16, DATE_TRUNC('day', CURRENT_TIMESTAMP) + interval '1 day' + TIME '10:55:00');
INSERT INTO schedule (route_id, bus_id, departure_datetime) VALUES (5, 1, DATE_TRUNC('day', CURRENT_TIMESTAMP) + interval '1 day' + TIME '11:25:00');
INSERT INTO schedule (route_id, bus_id, departure_datetime) VALUES (6, 29, DATE_TRUNC('day', CURRENT_TIMESTAMP) + interval '1 day' + TIME '18:10:00');
INSERT INTO schedule (route_id, bus_id, departure_datetime) VALUES (7, 3, DATE_TRUNC('day', CURRENT_TIMESTAMP) + interval '1 day' + TIME '15:10:00');
INSERT INTO schedule (route_id, bus_id, departure_datetime) VALUES (8, 17, DATE_TRUNC('day', CURRENT_TIMESTAMP) + interval '1 day' + TIME '17:00:00');
INSERT INTO schedule (route_id, bus_id, departure_datetime) VALUES (8, 15, DATE_TRUNC('day', CURRENT_TIMESTAMP) + interval '1 day' + TIME '10:55:00');
INSERT INTO schedule (route_id, bus_id, departure_datetime) VALUES (8, 18, DATE_TRUNC('day', CURRENT_TIMESTAMP) + interval '1 day' + TIME '15:00:00');
INSERT INTO schedule (route_id, bus_id, departure_datetime) VALUES (9, 13, DATE_TRUNC('day', CURRENT_TIMESTAMP) + interval '1 day' + TIME '19:50:00');
INSERT INTO schedule (route_id, bus_id, departure_datetime) VALUES (10, 9, DATE_TRUNC('day', CURRENT_TIMESTAMP) + interval '1 day' + TIME '15:00:00');
INSERT INTO schedule (route_id, bus_id, departure_datetime) VALUES (10, 2, DATE_TRUNC('day', CURRENT_TIMESTAMP) + interval '1 day' + TIME '11:45:00');
